### ISSUE TITLE
Feature Request: Separate H and X System Options

### ISSUE THREAD

**Issue by mmearly** [PumpedSardines/Tajpi#2]
I love Tajpi's autoconvert X-system support, but as far as I can tell enabling this also enables H-system support, which ("whiĉ" ;) ) is a bit annoying since I often need to type (e.g.) "ch" without it being converted to "ĉ", but I almost always want to convert "cx" to "ĉ". Would it be possible to separate out H-system support and X-system support into two separate options in the menu, much like how option+c is already a separate option? Dankon!

**Comment by PumpedSardines** [comment]
Hey, thanks for reaching out. Really fun that you're enjoying using Tajpi! 

Yes, that's definitely an oversight from my part. I personally don't use the automatic transform system, so I haven't really though of the possible problems with how tajpi handles that. 

I'll fix it right away!

**Comment by PumpedSardines** [comment]
Hey, this is now fixed in [release 1.2.0](https://github.com/PumpedSardines/Tajpi/releases/tag/1.2.0). Thanks for using Tajpi :)
